# Generated by Django 5.0.7 on 2024-07-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTripRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=255)),
                ('driver_name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('starting_mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ending_mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starting_location', models.CharField(max_length=255)),
                ('ending_location', models.CharField(max_length=255)),
                ('stop1_customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stop1_customer_address', models.CharField(blank=True, max_length=255, null=True)),
                ('stop1_pallets_in', models.IntegerField(blank=True, null=True)),
                ('stop1_pallets_out', models.IntegerField(blank=True, null=True)),
                ('stop1_comments', models.TextField(blank=True, null=True)),
                ('stop2_customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stop2_customer_address', models.CharField(blank=True, max_length=255, null=True)),
                ('stop2_pallets_in', models.IntegerField(blank=True, null=True)),
                ('stop2_pallets_out', models.IntegerField(blank=True, null=True)),
                ('stop2_comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelPurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('invoice_number', models.CharField(max_length=100)),
                ('gallons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dollar_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_stop_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
