# Generated by Django 5.0.7 on 2024-07-27 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_records', '0002_remove_drivertriprecord_stop1_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpurchaserecord',
            name='trip_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_purchase', to='trip_records.drivertriprecord'),
        ),
    ]
