# Generated by Django 5.0.7 on 2024-07-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_records', '0003_fuelpurchaserecord_trip_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertriprecord',
            name='manifest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drivertriprecord',
            name='trailer_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drivertriprecord',
            name='truck_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
