# Generated by Django 5.0.7 on 2024-07-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_records', '0004_drivertriprecord_manifest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertriprecord',
            name='company_address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
